services:
  frontend:
    build:
      context: ./frontend/pdfapp
      dockerfile: Dockerfile
      args:
        - REACT_APP_APP_HOST=localhost
        - REACT_APP_APP_PORT=8000
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend/pdfproject
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - mediafiles:/pdfproject/mediafiles
      - staticfiles:/pdfproject/staticfiles

volumes:
  mediafiles:
  staticfiles:
